name: Build Web (pygame)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: 3.1.56

    - name: Install python + pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Install pygame-web
      run: |
        pip install pygame-web

    - name: Build game wasm
      run: |
        python3 -m pygame_web.build game.py --output web

    - name: Upload artifact web
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: web
